version: "3.8"
services:
  ethereum-node:
    image: ethereum/client-go:v1.10.26
    container_name: ethereum-node
    ports:
      - "8545:8545"
      - "30303:30303"
    entrypoint: ["geth"]
    command:
      - "--dev"
      - "--http"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.api"
      - "eth,net,web3,personal,miner"
      - "--allow-insecure-unlock"

